import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider, UserButton } from "@clerk/nextjs";
import Sample from "../components/Sample";
import Topbar from "../components/Topbar";
import StarsCanvas from "../components/StarCanvas";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#030014]">
      <head>
      <link href="https://fonts.googleapis.com/css?family=Montserrat:100" rel="stylesheet"></link>
      </head>
      <ClerkProvider>
        <body className={`${inter.className} bg-[#030014] overflow-y-hidden overflow-x-hidden`}>
          <main>
           <Sample></Sample>
           <Topbar></Topbar>
           {children}
           <StarsCanvas></StarsCanvas>
          </main>
        </body>
      </ClerkProvider>
    </html>
  );
}
